### ISSUE TITLE
What is the best way to optimize mapping parameters, similar to what you presented in the paper?

### ISSUE THREAD

**Issue by lfaller** [Cibiv/Teaser#13]
Hello all,

I would like to evaluate how choosing different seed lengths for BWA mem would affect aligning reads to a yeast reference genome.

I modeled my `yeast.yaml` file on the `example_ecoli.yaml` file you provide and set it up as follows:

```
include:
  - base_teaser.yaml

teaser:
   tests:
      yeast_test:
         reference: yeast.fasta

evaluation:
   pos_threshold: 10

threads: 40

report: {name: yeast}
```

How can I specify that I want bwa-mem to use seed lengths from 18 to 30 nt?

Thanks for any guidance!

~Lina
